"""Add created_at to User

Revision ID: c2150ca60b67
Revises: 3493b0ca7e0e
Create Date: 2025-05-31 22:58:17.650801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2150ca60b67'
down_revision = '3493b0ca7e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
